### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Kotaro126** [Kotaro126/furima-30522#10]
# URL
https://furima-30522.herokuapp.com
# Basic認証のIDとパスワード
ID: admin
password: 2222
# 出品者用のアドレスとパスワード
1. アドレス：tes@tes　　　パスワード：test33
# 購入者用のアドレスとパスワード
2. アドレス：test@test　　パスワード：test22
# 購入用カードの番号・期限・セキュリティコード
番号：4242424242424242
期限：12月/2024年
セキュリティコード：123

**Comment by mutorisa** [comment]
平松さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by Kotaro126** [comment]
@mutorisa 
挙動確認ありがとうございました！LGTM大変嬉しいです！
